### ISSUE TITLE
models_check should cut events before loading them in 

### ISSUE THREAD

**Issue by JelleAalbers** [FlamTeam/flamedisx-notebooks#1]
Found by @plt109: models_check does not initialize following https://github.com/FlamTeam/flamedisx/pull/69. Likely it goes wrong when trying to annotate out-of-bounds data that should be cut out first.

**Comment by pelssers** [comment]
Solved in https://github.com/FlamTeam/flamedisx-notebooks/commit/1a9f9f396eb9d01cb529ae11df2029d9585c23a8

Cutting events with non-positive s1 and s2 acceptance before initializing the sources, uses the acceptance functions from the desired source class instead to a simple energy range cut to handle nontrivial acceptance functions.

Notebook updated and committed with output, closing issue.
