### ISSUE TITLE
Tutorial fits not stable / working

### ISSUE THREAD

**Issue by JelleAalbers** [FlamTeam/flamedisx-notebooks#2]
Reported by @jordan-palmer and @plt109: some of the example fits in the tutorial do not work. The electron lifetime often just comes out at the guess, and the ER model in the 'modelling 2' section is so  far from the model the data is simulated with that events get an infinite likelihood.

**Comment by pelssers** [comment]
I'm looking into this now, already in Tutorial section "2. Inference" the `ll.bestfit` always ends up with the `elife` guess. I'll try and isolate the problem.

**Comment by pelssers** [comment]
The problem with the non-varying elife seems to be related to it having a vary small gradient compared to the rate multiplier. The default SciPy optimizer method (`trust-constr`) doesn't vary it at all, when using TNC it does vary the elife correctly.
One can try TNC by passing `optimizer_kwargs=dict(method='TNC')` to the bestfit call. This would also explain why the tutorial worked well before when TNC was the default.

Here is the history of the bestfit calls to the optimizer:

Default case using `trust-contr`:

|    |   er_rate_multiplier |   elife |       y |   er_rate_multiplier_grad |   elife_grad |
|---:|---------------------:|--------:|--------:|--------------------------:|-------------:|
|  0 |            0.03      |  490000 | 378.149 |                 297.346   |  0.000181388 |
|  1 |            0.0267322 |  490000 | 377.447 |                 126.206   |  0.000181096 |
|  2 |            0.0248033 |  490000 | 377.318 |                   4.02471 |  0.000180924 |

When using `TNC`:

|    |   er_rate_multiplier |   elife |       y |   er_rate_multiplier_grad |   elife_grad |
|---:|---------------------:|--------:|--------:|--------------------------:|-------------:|
|  0 |            0.03      |  490000 | 378.149 |               297.346     |  0.000181388 |
|  1 |            0.0296585 |  489953 | 378.042 |               281.22      |  0.000181218 |
|  2 |            0.023182  |  489059 | 377.237 |              -114.485     |  0.000177972 |
|  3 |            0.026591  |  489529 | 377.344 |               117.823     |  0.000179685 |
|  4 |            0.0248865 |  489294 | 377.192 |                 9.62292   |  0.00017883  |
|  5 |            0.0248868 |  489244 | 377.183 |                 9.63429   |  0.000178679 |
|  6 |            0.0251665 |  429594 | 373.723 |                23.0613    | -0.000101795 |
|  7 |            0.0250265 |  459444 | 373.396 |                16.3947    |  6.7901e-05  |
|  8 |            0.0250965 |  444519 | 372.928 |                19.741     | -7.83153e-06 |
|  9 |            0.0250964 |  444520 | 372.928 |                19.7323    | -7.8275e-06  |
| 10 |            0.0248258 |  445965 | 372.92  |                 1.61974   |  2.09769e-07 |
| 11 |            0.0244389 |  445953 | 372.924 |               -25.1644    |  1.1268e-07  |
| 12 |            0.0248023 |  445964 | 372.92  |                 0.0178375 |  2.03799e-07 |

**Comment by JelleAalbers** [comment]
Thanks Bart! Maybe trust-constr isn't scaling the dimensions? We could check that e.g. by specifying the elife in ms.

**Comment by pelssers** [comment]
Good idea, it seems that `trust-constr` doesn't scale the dimensions, specifying `elife` in milliseconds results in comparable gradients and the right answer:

|    |   er_rate_multiplier |    elife |       y |   er_rate_multiplier_grad |     elife_grad |
|---:|---------------------:|---------:|--------:|--------------------------:|---------------:|
|  0 |            0.03      | 0.41     | 378.159 |                295.688    | -262.416       |
|  1 |            0.0267284 | 0.437944 | 373.33  |                125.353    |  -47.9797      |
|  2 |            0.024808  | 0.445692 | 373.01  |                  4.00208  |   -2.60432     |
|  3 |            0.024808  | 0.446162 | 373.009 |                  4.01973  |   -0.00858402  |
|  4 |            0.0247611 | 0.446164 | 373.009 |                  0.807625 |    0.000790119 |
|  5 |            0.0247516 | 0.446164 | 373.009 |                  0.161636 |   -0.000110626 |

**Comment by jordan-palmer** [comment]
Thank you! including the `optimizer_kwargs=dict(method='TNC')` argument removes the degeneracy issue for me too

**Comment by JelleAalbers** [comment]
This was fixed by https://github.com/FlamTeam/flamedisx/pull/72 and https://github.com/FlamTeam/flamedisx/pull/76.
